version: '3.8'

services:
  app:
    image: azizyogo/test-telkomsel:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./.env.yaml:/app/.env.yaml

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
